version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: backend
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_admin
    ports:
      - "6379:6379"
