export const users = [
    {
      id: 1,
      name: "Alice Johnson",
      age: 28,
      isActive: true,
      balance: 2540.75,
      picture: "https://randomuser.me/api/portraits/women/1.jpg",
      eyeColor: "blue",
      gender: "female",
      email: "alice.johnson@example.com",
      phone: "+1 (800) 555-1234",
      address: "123 Main St, Springfield, IL 62701"
    },
    {
      id: 2,
      name: "Bob Smith",
      age: 35,
      isActive: false,
      balance: 1876.45,
      picture: "https://randomuser.me/api/portraits/men/2.jpg",
      eyeColor: "brown",
      gender: "male",
      email: "bob.smith@example.com",
      phone: "+1 (800) 555-5678",
      address: "456 Elm St, Springfield, IL 62702"
    },
    {
      id: 3,
      name: "Carol Williams",
      age: 22,
      isActive: true,
      balance: 3200.00,
      picture: "https://randomuser.me/api/portraits/women/3.jpg",
      eyeColor: "green",
      gender: "female",
      email: "carol.williams@example.com",
      phone: "+1 (800) 555-9876",
      address: "789 Oak St, Springfield, IL 62703"
    },
    {
      id: 4,
      name: "David Brown",
      age: 40,
      isActive: true,
      balance: 5000.00,
      picture: "https://randomuser.me/api/portraits/men/4.jpg",
      eyeColor: "blue",
      gender: "male",
      email: "david.brown@example.com",
      phone: "+1 (800) 555-3456",
      address: "101 Maple St, Springfield, IL 62704"
    },
    {
      id: 5,
      name: "Eve Davis",
      age: 30,
      isActive: false,
      balance: 1500.00,
      picture: "https://randomuser.me/api/portraits/women/5.jpg",
      eyeColor: "hazel",
      gender: "female",
      email: "eve.davis@example.com",
      phone: "+1 (800) 555-7890",
      address: "202 Pine St, Springfield, IL 62705"
    },
    {
      id: 6,
      name: "Frank Miller",
      age: 45,
      isActive: true,
      balance: 3750.25,
      picture: "https://randomuser.me/api/portraits/men/6.jpg",
      eyeColor: "gray",
      gender: "male",
      email: "frank.miller@example.com",
      phone: "+1 (800) 555-4321",
      address: "303 Cedar St, Springfield, IL 62706"
    },
    {
      id: 7,
      name: "Grace Wilson",
      age: 29,
      isActive: true,
      balance: 2200.50,
      picture: "https://randomuser.me/api/portraits/women/7.jpg",
      eyeColor: "blue",
      gender: "female",
      email: "grace.wilson@example.com",
      phone: "+1 (800) 555-6543",
      address: "404 Birch St, Springfield, IL 62707"
    },
    {
      id: 8,
      name: "Hank Taylor",
      age: 33,
      isActive: false,
      balance: 1420.75,
      picture: "https://randomuser.me/api/portraits/men/8.jpg",
      eyeColor: "brown",
      gender: "male",
      email: "hank.taylor@example.com",
      phone: "+1 (800) 555-3210",
      address: "505 Walnut St, Springfield, IL 62708"
    },
    {
      id: 9,
      name: "Ivy Anderson",
      age: 27,
      isActive: true,
      balance: 3000.00,
      picture: "https://randomuser.me/api/portraits/women/9.jpg",
      eyeColor: "green",
      gender: "female",
      email: "ivy.anderson@example.com",
      phone: "+1 (800) 555-8765",
      address: "606 Chestnut St, Springfield, IL 62709"
    },
    {
      id: 10,
      name: "Jack Harris",
      age: 38,
      isActive: false,
      balance: 2100.50,
      picture: "https://randomuser.me/api/portraits/men/10.jpg",
      eyeColor: "blue",
      gender: "male",
      email: "jack.harris@example.com",
      phone: "+1 (800) 555-5432",
      address: "707 Hickory St, Springfield, IL 62710"
    }
  ];
  